name: get_comics
description: Gets comics from comics.com
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  dcli: ^1.5.3
  html: ^0.15.0
  mailer: ^5.0.0
  yaml: ^3.1.0


dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.0
