name: get_comics
description: Gets comics from comics.com
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  dcli: ^1.5.3
  googleapis_auth: ^1.1.0
  mailer: ^5.0.0
  universal_html: ^2.0.8
  yaml: ^3.1.0


dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
