name: get_comics
description: Gets comics from comics.com
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  args: ^2.4.2
  dio: ^5.3.3
  html: ^0.15.0
  http_mock_adapter: ^0.6.0
  mailer: ^6.0.1
  yaml: ^3.1.0
  intl: ^0.18.0


dev_dependencies:
  build_runner: any
  build_test: any
  mockito: any
  lints: ^5.1.1
  test: ^1.20.0
  # pedantic: ^1.11.1
  # test_coverage: ^0.4.2
  # test_coverage: 
    # git: 
    #   url: https://github.com/timsneath/test-coverage
    #   ref: 38ac26907341cead0f36f01582d08133369655d3
  

