# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Cross

on:
  workflow_dispatch:

jobs:
  arm64_job:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Version  
        id: version  
        uses: juliansangillo/tag-version@v1  
        with:  
            production-branch: release
            test-branch: test  
            dev-branch: master

      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run Commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds
          githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"
          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: get-comics-${{ matrix.distro }}_${{ matrix.arch }}
          # The shell to run commands with in the container
          shell: /bin/sh
          install: |
            apt-get update -q -y && apt-get install -q -y wget bash unzip git
            wget https://storage.googleapis.com/dart-archive/channels/stable/release/2.13.3/sdk/dartsdk-linux-arm64-release.zip
            unzip dartsdk-linux-arm64-release.zip
            rm dartsdk-linux-arm64-release.zip
          
          run: |
            /dart-sdk/bin/dart pub get
            /dart-sdk/bin/dart compile exe -o /artifacts/${artifact_name} bin/get_comics.dart 

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
