# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  release:
    types: [published]
  workflow_dispatch:


permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: dart-lang/setup-dart@v1
      - name: Get Dependancies
        run: dart pub get
      # - name: Upgrade Dependancies
      #   run: dart pub upgrade
      - name: Analyze
        run: dart analyze
      - name: Test
        run: dart test
      - name: Build
        run: dart compile exe -o get-comics-x86-64 bin/get_comics.dart

      - name: Release
        uses: SierraSoftworks/gh-releases@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: 'true'
          files: |
            get-comics-x86-64

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: harbor.winters.org.nz
          username: robot$github
          password: ${{ secrets.HARBOR }}
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            harbor.winters.org.nz/public/get-comics:latest
            harbor.winters.org.nz/public/get-comics:${{github.ref_name}}
